-- Delicias de Bávaro: menú, pedidos y acceso administrativo.
-- Ejecuta esta migración en Supabase SQL Editor antes de desplegar la integración.

create table if not exists public.restaurant_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.menu_categories (
  id text primary key check (id ~ '^[a-z0-9_]{2,64}$'),
  name_es text not null check (char_length(trim(name_es)) > 0),
  name_en text not null check (char_length(trim(name_en)) > 0),
  sort_order integer not null default 0,
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  category_id text not null references public.menu_categories(id) on delete restrict,
  name_es text not null check (char_length(trim(name_es)) > 0),
  name_en text not null check (char_length(trim(name_en)) > 0),
  description_es text not null default '',
  description_en text not null default '',
  price numeric(10,2) not null check (price > 0),
  image_url text not null default '',
  sort_order integer not null default 0,
  is_available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  table_number text not null check (char_length(trim(table_number)) between 1 and 32),
  customer_language text not null check (customer_language in ('es', 'en')),
  status text not null default 'new' check (status in ('new', 'in_kitchen', 'ready', 'delivered', 'cancelled')),
  total numeric(10,2) not null check (total > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  menu_item_id bigint references public.menu_items(id) on delete set null,
  name_es text not null,
  name_en text not null,
  unit_price numeric(10,2) not null check (unit_price > 0),
  quantity integer not null check (quantity > 0 and quantity <= 50),
  created_at timestamptz not null default now()
);

create index if not exists menu_items_category_sort_idx
  on public.menu_items(category_id, sort_order);
create index if not exists orders_status_created_idx
  on public.orders(status, created_at desc);
create index if not exists order_items_order_idx
  on public.order_items(order_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists menu_categories_set_updated_at on public.menu_categories;
create trigger menu_categories_set_updated_at
before update on public.menu_categories
for each row execute function public.set_updated_at();

drop trigger if exists menu_items_set_updated_at on public.menu_items;
create trigger menu_items_set_updated_at
before update on public.menu_items
for each row execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

create or replace function public.is_restaurant_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1
    from public.restaurant_admins
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_restaurant_admin() from public;
grant execute on function public.is_restaurant_admin() to anon, authenticated;

alter table public.restaurant_admins enable row level security;
alter table public.menu_categories enable row level security;
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Administrators can view themselves" on public.restaurant_admins;
create policy "Administrators can view themselves"
on public.restaurant_admins for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Public can view visible categories" on public.menu_categories;
create policy "Public can view visible categories"
on public.menu_categories for select to anon, authenticated
using (is_visible = true);

drop policy if exists "Admins manage categories" on public.menu_categories;
create policy "Admins manage categories"
on public.menu_categories for all to authenticated
using ((select public.is_restaurant_admin()))
with check ((select public.is_restaurant_admin()));

drop policy if exists "Public can view available menu items" on public.menu_items;
create policy "Public can view available menu items"
on public.menu_items for select to anon, authenticated
using (is_available = true);

drop policy if exists "Admins manage menu items" on public.menu_items;
create policy "Admins manage menu items"
on public.menu_items for all to authenticated
using ((select public.is_restaurant_admin()))
with check ((select public.is_restaurant_admin()));

drop policy if exists "Admins manage orders" on public.orders;
create policy "Admins manage orders"
on public.orders for all to authenticated
using ((select public.is_restaurant_admin()))
with check ((select public.is_restaurant_admin()));

drop policy if exists "Admins view order items" on public.order_items;
create policy "Admins view order items"
on public.order_items for select to authenticated
using ((select public.is_restaurant_admin()));
